# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 5.0.201
      
      # Run tests 
      - name: Test
        run: dotnet test
      
      # Generate website
      - name: Publish
        run: dotnet publish samples/Blazor.BwipJs.Samples/Blazor.BwipJs.Samples.csproj --configuration Release --output build
        
      # Publish website
      - name: GitHub Pages action
        # Publish only when the push is on master
        if: ${{ github.ref == 'refs/heads/master' }}
        # You may pin to the exact commit or the version.
        # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          # Set a generated GITHUB_TOKEN for pushing to the remote branch.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Set an input directory for deployment.
          publish_dir: build/wwwroot
          # Keep only the latest commit on a GitHub Pages branch
          force_orphan: true
